# Site settings
title: Brad Wilson
email: brad@lucky-dip.net
description: > # this means to ignore newlines until "baseurl:"
  A curious individual (in more than one sense) who loves learning and
  thinks this whole damn world is amazing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.lucky-dip.net" # the base hostname & protocol for your site
twitter_username: bradx3
github_username:  bradx3

# Build settings
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
exclude: [vendor]
permalink: /articles/:year/:month/:day/:title