# Site settings
title: Brad Wilson
email: brad@lucky-dip.net
description: > # this means to ignore newlines until "baseurl:"
  A developer and team leader who loves Ruby, HTML and Javascript.
  Everything programming related not I think about it...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lucky-dip.net" # the base hostname & protocol for your site
twitter_username: bradx3
github_username:  bradx3

# Build settings
exclude: [vendor]
